
function LondoBell()
    self.clearButtons()
    faction = 'LondoBell'
    self.createButton({click_function = 'LondoBellCCA', function_owner = self, label = 'CCA', position = {-1.5, 4, 0},  rotation = {-60, 0, 0}, width=1200, height=400, font_size=250})
    self.createButton({click_function = 'LondoBellUC', function_owner = self, label = 'UC', position = {1.5, 4, 0},  rotation = {-60, 0, 0}, width=1200, height=400, font_size=250})
    self.createButton({click_function = 'UC', function_owner = self, label = 'Back', position = {0, 3, 0},  rotation = {-60, 0, 0}, width=1200, height=400, font_size=250})
end

function LondoBellUC()
  self.clearButtons()
  self.createButton({click_function = 'RX_0', function_owner = self, label = 'RX-0', position = {0, 4, 0},  rotation = {-60, 0, 0}, width=1200, height=400, font_size=250})
  self.createButton({click_function = 'LondoBell', function_owner = self, label = 'Back', position = {0, 3, 0},  rotation = {-60, 0, 0}, width=1200, height=400, font_size=250})
end
function LondoBellCCA()
  self.clearButtons()
  self.createButton({click_function = 'LondoBell', function_owner = self, label = 'Back', position = {0, 3, 0},  rotation = {-60, 0, 0}, width=1200, height=400, font_size=250})
end

--[[Londo Bell MS --]]
function RX_0()
  unit = 'rx-0'
  getThatRobot()
end
